version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: goals-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env

  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/app
    depends_on:
      - db
      - web
