# Generated by Django 4.0.9 on 2023-08-25 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('assigned_to', models.CharField(max_length=50, null=True)),
                ('starts_on', models.DateTimeField(null=True)),
                ('ends_on', models.DateTimeField(null=True)),
                ('percentage_completed', models.IntegerField(default=0)),
                ('assigned_by', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=70)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
