# Generated by Django 4.0.9 on 2023-05-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goal_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='usergoal',
            old_name='percentageCompleted',
            new_name='percentage_completed',
        ),
        migrations.RenameField(
            model_name='usergoal',
            old_name='userId',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goalType',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='assignedBy',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='endsOn',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='startsOn',
        ),
        migrations.AddField(
            model_name='goal',
            name='created_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='assigned_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='ends_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='starts_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
