# Generated by Django 4.0.7 on 2023-04-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token_Custom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('auth_token', models.CharField(max_length=40, verbose_name='Auth Token')),
                ('user_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('token_created', models.DateTimeField(auto_now_add=True, verbose_name='Token Created')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
