# Generated by Django 4.0.9 on 2023-08-20 11:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authCustom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token_custom',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='token_custom',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='token_custom',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='token_custom',
            name='user_id',
            field=models.CharField(max_length=80),
        ),
    ]
