version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: goals-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=goals-password
      - POSTGRES_DB=goals-db
      - POSTGRES_USER=goals-user
