# Generated by Django 4.0.9 on 2023-08-25 19:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_token', models.CharField(blank=True, max_length=40, verbose_name='Auth Token')),
                ('user_id', models.CharField(max_length=80)),
                ('token_created', models.DateTimeField(auto_now_add=True, verbose_name='Token Created')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
